version: '3'
services:
  webapp:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=database
      - PORT=3000
      - DB_USERNAME=postgres
      - DB_PASSWORD=admin
      - DB_NAME=weatherapp
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=weatherapp
    ports:
      - "5432:5432"
      
volumes:
  db-data: